In [ ]:
import numpy as np

Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?

In [ ]:
#è una matrice
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [ ]:
type(mat)

list

In [ ]:
#in primo luogo si considera che gli elementi sono rappresentati da 3 liste
#per accedere all'elemento si può fare indicando la posizione dell'indice dell'elemento

mat[2] #accedo al terzo elemento con l'indice 2

[10, 11, 12, 13, 14]

In [ ]:
#trasformazione della lista in array
mat = np.array(mat)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#anche nel caso dell'array si accede come nella lista con l'indice,dando la posizione dell'elemento, in questo caso accedo al secondo elemento con 1
mat[1]

array([5, 6, 7, 8, 9])

Abbiamo il seguente array NumPy: linear_data = np.array([x for x in range(27)]) Lo ridimensioniamo mediante il metodo .reshape(): reshaped_data = linear_data.reshape((3, 3, 3)) Quante dimensioni ha il nuovo array? Come facciamo per accedere ai singoli elementi?

In [ ]:
linear_data = np.array([x for x in range(27)])
reshaped_data = linear_data.reshape(3, 3, 3)

In [ ]:
linear_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
reshaped_data

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#ha tre dimensioni
len(reshaped_data)

3

In [ ]:
#per accedere agli elementi lo si fa con l'indicizzazione tridimensionale:
reshaped_data[0,1,2] #per esempio, 0 va' alla prima dimensione, 1 rappresenta la seconda riga infine 2 la terza colonna

5

 In una catena di montaggio abbiamo una struttura metallica di 28.75 cm di lunghezza; per assicurarne la stabilità, è necessario inserire 15 rivetti, dei quali uno all'inizio e uno alla fine, e tutti quanti separati dalla stessa distanza; come possiamo calcolare i punti esatti in cui inserire i rivetti tramite NumPy?

In [ ]:
print(np.linspace(0, 28.75,15)) #in questo caso 0 rappresenta il punto inziale, 28.75 è la distanza richiesta e 15 sono gli elementi da inserire

[ 0.          2.05357143  4.10714286  6.16071429  8.21428571 10.26785714
 12.32142857 14.375      16.42857143 18.48214286 20.53571429 22.58928571
 24.64285714 26.69642857 28.75      ]


Creiamo un ndarray con gli stessi valori. Ci sono due modalità: inizializzare un array e poi inserire i valori nelle posizioni adatte, oppure creare una lista di liste e poi effettuare un casting.

In [ ]:
# I modalità:
#inizializzazione dell'array
ar = np.array([1, 1, 1, 1, 5, 1, 1, 1, 20, -4, 0, 42])
ar

array([ 1,  1,  1,  1,  5,  1,  1,  1, 20, -4,  0, 42])

In [ ]:
#trasformazione in matrice
mat = ar.reshape(3,4)
mat

array([[ 1,  1,  1,  1],
       [ 5,  1,  1,  1],
       [20, -4,  0, 42]])

In [ ]:
# II modalità:
#creazione di una lista di liste
ar = np.array([[1, 1, 1, 1,],[5, 1, 1, 1,],[20, -4, 0, 42]] )
ar

array([[ 1,  1,  1,  1],
       [ 5,  1,  1,  1],
       [20, -4,  0, 42]])

Creiamo l'array Per ogni valore, sottraiamo il minimo (2) e poi dividiamo il risultato per il massimo (42) meno il minimo.

In [ ]:
ar2 = np.array([10, 22, 21, 8, 9, 9, 42, 3, 18, 11, 5, 4, 30, 12, 29, 37, 31, 7, 2, 26, 8, 6, 4, 33, 15])
ar2

array([10, 22, 21,  8,  9,  9, 42,  3, 18, 11,  5,  4, 30, 12, 29, 37, 31,
        7,  2, 26,  8,  6,  4, 33, 15])

In [ ]:
minimo=ar2.min()
minimo

2

In [ ]:
massimo=ar2.max()
massimo

42

In [ ]:
for el in ar2:
    risultato = el - minimo
    risultato2= risultato/massimo
    risultato3=risultato2-minimo
    print(risultato3)

-1.8095238095238095
-1.5238095238095237
-1.5476190476190477
-1.8571428571428572
-1.8333333333333333
-1.8333333333333333
-1.0476190476190477
-1.9761904761904763
-1.619047619047619
-1.7857142857142858
-1.9285714285714286
-1.9523809523809523
-1.3333333333333335
-1.7619047619047619
-1.3571428571428572
-1.1666666666666665
-1.3095238095238095
-1.880952380952381
-2.0
-1.4285714285714286
-1.8571428571428572
-1.9047619047619047
-1.9523809523809523
-1.2619047619047619
-1.6904761904761905
